name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Packages
        run: npm install
      - name: Building the App and Compressing the output
        run: npm run build-compress
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - run: azcopy copy ./dist-compressed/dotnetthoughts/ https://dotnetthoughts.blob.core.windows.net/$web/ --recursive=true --content-encoding="GZip"
          