name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Packages
        run: npm install
      - name: Run a multi-line script
        run: npm run build-compress
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - run: |
          az storage file upload-batch --connection-string ${{ secrets.STORAGE_CONNECTION_STRING }} --destination https://dotnetthoughts.blob.core.windows.net/$web/ --source ./dist-compressed/dotnetthoughts --content-encoding "GZip" --pattern "*.js","*.css","*.html"