name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Packages
        run: npm install
      - name: Building the App and Compressing the output
        run: npm run build-compress
      - name: Upload to blob storage
        uses: azure/CLI@v1
        with:
          inlineScript: |
              az storage blob upload-batch --account-name calltoactionsweb -d '$web' -s ./dist/dotnetthoughts/ --overwrite=true --account-key=${{ secrets.STORAGE_ACCOUNT_KEY }}
              az storage blob upload-batch --account-name calltoactionsweb -d '$web' -s ./dist-compressed/dotnetthoughts/ --overwrite=true --content-encoding="GZip" --pattern="*.js" --content-type="application/javascript" --account-key=${{ secrets.STORAGE_ACCOUNT_KEY }}
              az storage blob upload-batch --account-name calltoactionsweb -d '$web' -s ./dist-compressed/dotnetthoughts/ --overwrite=true --content-encoding="GZip" --pattern="*.css" --content-type="text/css" --account-key=${{ secrets.STORAGE_ACCOUNT_KEY }}
              az storage blob upload-batch --account-name calltoactionsweb -d '$web' -s ./dist-compressed/dotnetthoughts/ --overwrite=true --content-encoding="GZip" --pattern="*.html" --content-type="text/html" --account-key=${{ secrets.STORAGE_ACCOUNT_KEY }}
